name: Random Cron
# 已禁用定时任务相关功能
on:
  workflow_dispatch:  # 仅保留手动触发，用于测试
  # workflow_run:
  #   workflows: ["刷步数"]
  #   types:
  #     - completed

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
      - name: random cron
        run: |
          source cron_convert.sh
          echo "configed CRON_HOURS ${{ vars.CRON_HOURS }}"
          persist_execute_log ${{ github.event_name }} ${{ vars.CRON_HOURS }}
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          current=`TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S'`
          git commit -m "[${current}] random cron trigger by ${{ github.event_name }}"
          git push origin master
